"use client";

import { useMemo, useState } from "react";
import type { FileNode } from "@/lib/architect/agent-sim";
import { ChevronRight, File, Folder, FolderOpen, TerminalSquare } from "lucide-react";
import { cn } from "@/lib/utils";

function flatten(nodes: FileNode[]): FileNode[] {
  return nodes.flatMap((n) => (n.kind === "dir" ? flatten(n.children ?? []) : [n]));
}

function fakeSource(file: FileNode, projectName: string): string {
  const name = file.path.split("/").pop() ?? file.path;
  switch (file.language) {
    case "tsx":
      return `export default function ${name.replace(/\.[tj]sx?$/, "")}() {\n  return (\n    <section className="mx-auto max-w-3xl px-6 py-16">\n      <h1 className="text-3xl font-semibold">${projectName}</h1>\n      <p className="mt-2 text-neutral-500">Generated by Architect from your prompt.</p>\n    </section>\n  );\n}\n`;
    case "ts":
      return `// ${file.path}\nexport async function run(input: string) {\n  const plan = await planner.plan(input);\n  for (const step of plan.steps) {\n    await tools.execute(step);\n  }\n  return plan.summary;\n}\n`;
    case "css":
      return `:root {\n  --accent: #f2a93b;\n}\n\nbody {\n  font-family: system-ui, sans-serif;\n}\n`;
    case "json":
      return `{\n  "name": "${projectName.toLowerCase().replace(/\s+/g, "-")}",\n  "private": true,\n  "scripts": { "dev": "next dev", "build": "next build" }\n}\n`;
    default:
      return `# ${projectName}\n\nGenerated by Architect 2.0 from a single prompt.\n`;
  }
}

export function CodePanel({ files, projectName }: { files: FileNode[]; projectName: string }) {
  const flatFiles = useMemo(() => flatten(files), [files]);
  const [selected, setSelected] = useState<string>(flatFiles[0]?.path ?? "");
  const active = flatFiles.find((f) => f.path === selected) ?? flatFiles[0];

  return (
    <div className="grid h-full min-h-0 grid-cols-[200px_1fr]">
      <div className="scrollbar-thin overflow-y-auto border-r border-border-subtle p-2">
        <Tree nodes={files} selected={selected} onSelect={setSelected} depth={0} />
      </div>
      <div className="flex min-h-0 flex-col">
        <div className="flex items-center gap-2 border-b border-border-subtle px-3 py-2 font-mono text-xs text-text-muted">
          <File className="size-3.5" /> {active?.path ?? "—"}
        </div>
        <pre className="scrollbar-thin flex-1 overflow-auto px-4 py-3 font-mono text-[13px] leading-relaxed text-text-muted">
          <code>{active ? fakeSource(active, projectName) : "// Nothing built yet"}</code>
        </pre>
        <div className="flex items-center gap-2 border-t border-border-subtle bg-bg-raised-2 px-3 py-2 font-mono text-xs text-text-faint">
          <TerminalSquare className="size-3.5" />
          <span className="text-success">$</span> npm run dev
          <span className="ml-2 text-text-faint">ready on :3000 — watching for file changes</span>
        </div>
      </div>
    </div>
  );
}

function Tree({
  nodes,
  selected,
  onSelect,
  depth,
}: {
  nodes: FileNode[];
  selected: string;
  onSelect: (path: string) => void;
  depth: number;
}) {
  return (
    <ul className="text-sm">
      {nodes.map((n) => (
        <TreeNode key={n.path} node={n} selected={selected} onSelect={onSelect} depth={depth} />
      ))}
    </ul>
  );
}

function TreeNode({
  node,
  selected,
  onSelect,
  depth,
}: {
  node: FileNode;
  selected: string;
  onSelect: (path: string) => void;
  depth: number;
}) {
  const [open, setOpen] = useState(true);
  const name = node.path.split("/").pop();

  if (node.kind === "dir") {
    return (
      <li>
        <button
          onClick={() => setOpen((v) => !v)}
          className="flex w-full items-center gap-1 rounded px-1.5 py-1 text-text-muted hover:bg-bg-raised-2"
          style={{ paddingLeft: depth * 12 + 6 }}
        >
          <ChevronRight className={cn("size-3 transition-transform", open && "rotate-90")} />
          {open ? <FolderOpen className="size-3.5 text-blue" /> : <Folder className="size-3.5 text-blue" />}
          {name}
        </button>
        {open && node.children && (
          <Tree nodes={node.children} selected={selected} onSelect={onSelect} depth={depth + 1} />
        )}
      </li>
    );
  }

  return (
    <li>
      <button
        onClick={() => onSelect(node.path)}
        className={cn(
          "flex w-full items-center gap-1.5 rounded px-1.5 py-1 text-left hover:bg-bg-raised-2",
          selected === node.path ? "bg-bg-raised-2 text-text" : "text-text-muted",
        )}
        style={{ paddingLeft: depth * 12 + 22 }}
      >
        <File className="size-3.5" /> {name}
      </button>
    </li>
  );
}
